apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repoName }}
  description: Private OpenShift AI GPU Chatbot
  annotations:
    github.com/project-slug: your-github-org/${{ values.repoName }}
spec:
  type: service
  lifecycle: experimental
  owner: user:guest