---
# Service Mesh 2 Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# Service Mesh 3 (Sail) Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator3
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: sailoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# Service Mesh 2 Instance (Required for ODS KServe currently)
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"