---
apiVersion: v1
kind: Namespace
metadata:
  name: workshop-maas
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: granite-8b-code-instruct
    serving.knative.openshift.io/enablePassthrough: 'true'
    serving.kserve.io/deploymentMode: Serverless
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    argocd.argoproj.io/sync-wave: "6"
  name: granite-8b-code-instruct
  namespace: workshop-maas
  labels:
    networking.knative.dev/visibility: cluster-local
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 2
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '10'
          memory: 20Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '6'
          memory: 16Gi
          nvidia.com/gpu: '1'
      runtime: granite-8b-code-instruct
      storageUri: 'oci://registry.redhat.io/rhelai1/modelcar-granite-8b-code-instruct:1.4.0'